# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_imagedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='image',
            field=models.ImageField(default='Uno', upload_to=''),
            preserve_default=False,
        ),
    ]
