# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_imagedata_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdata',
            name='event_image_url',
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles_api.ImageData'),
            preserve_default=False,
        ),
    ]
