# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0007_auto_20171007_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopledata',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.ImageData'),
        ),
        migrations.AlterField(
            model_name='placedata',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.ImageData'),
        ),
        migrations.AlterField(
            model_name='sketchdata',
            name='image_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.ImageData'),
        ),
    ]
