# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-14 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0008_auto_20171007_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytypedata',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles_api.ImageData'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
