# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0009_auto_20171014_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytypedata',
            name='show_speakers_in_app',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitydata',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='placedata',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='streamdata',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
